### ISSUE TITLE
How are neighbours supposed to be able to connect back to your node when kube firewalls the ip and doesn't expose the port externally?

### ISSUE THREAD

**Issue by brandoncollins7** [toonsevrin/kubeIRI#1]

**Comment by toonsevrin** [comment]
It's been a while since i've worked with iota/k8s, so my answer may not be helpful. The config defines the following service:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: iri
  labels:
    app: iri
spec:
  ports:
    - port: 14800
    - port: 15600
    - port: 14265
  selector:
    app: iri
  type: ClusterIP
```

I'm not sure why I chose for a ClusterIP there, you could try using a NodePort (and just maybe a loadbalancer).
